$env:xDLOD_REF="false"                       
$env:TIMEOUT="30.0"

 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r
 .\enso_opt.exe r

$env:TIMEOUT="4000000.0"